# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sound Women United
email: soundwomenunited@gmail.com
domain: sabord.github.io
url: https://sabord.github.io
baseurl: /swu
description: >-
  Sound Women United (SWU) est un réseau d'artistes féminines 
  issues de la culture reggae dub. 
  Notre réseau réunit des selectas, operators, productrices, 
  musiciennes, chanteuses, MCs, dub poétesses, photographes et peintres.
meta_author: Sound Women United

# Collections
collections:
  artists:
    output: true
    permalink: /:name/

# Social media links order
link_order: ["instagram", "facebook", "tiktok", "spotify", "soundcloud", "youtube", "deezer", "bandcamp", "mixcloud", "apple"]

# Footer settings
footer:
  copyright: Sound Women United

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
